version: "3.9"
services:
  app:
    build: .
    image: streamlit:latest
    container_name: tides-streamlit
    hostname: tides
    restart: always
    ports:
      - 8501:8501
    volumes:
      - ./:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Sao_Paulo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - autoheal=true
    healthcheck:
      test: /app/healthcheck.py
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 10s
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 20s
      placement:
        constraints:
          - node.role==manager
