version: "3.9"
services:
  app:
    build: .
    image: ${HOST}-streamlit:latest
    container_name: ${HOST}-streamlit
    hostname: ${HOST}
    restart: always
    ports:
      - ${PORT}:8501
    volumes:
      - ./data:/app/data
      - ./tides-st.py:/app/main.py
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - autoheal=true
    healthcheck:
      test: /app/healthcheck.py
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 10s
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 20s
      placement:
        constraints:
          - node.role==manager
