version: "3.9"
services:
  app:
    build: .
    image: tides-streamlit:latest
    container_name: tides-streamlit
    hostname: tides
    ports:
      - 8501:8501
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 20s
      placement:
        constraints:
          - node.role==manager
